# Generated by Django 4.2.6 on 2023-11-21 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_avatar_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(default='/static/assets/avatar.webp', upload_to='avatars'),
        ),
    ]
