# Generated by Django 4.2.6 on 2023-11-07 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('super_teacher', '0003_remove_professor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='photo',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
