# Generated by Django 4.2.6 on 2023-11-07 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('super_teacher', '0004_professor_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='photo',
        ),
    ]
